name: Main CI/CD

on:
  push:
    branches: [main]

jobs:
  test-and-scan:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm run test:cov

  release:
    needs: test-and-scan
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Kaniko Config
        run: |
          mkdir -p /tmp/kaniko
          cat > /tmp/kaniko/config.json <<EOF
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n '${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}' | base64)"
              }
            }
          }
          EOF

      - name: Build & Push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.23.2-debug
        with:
          args: >-
            --context=${{ github.workspace }}
            --dockerfile=${{ github.workspace }}/Dockerfile
            --destination=ghcr.io/${{ github.repository_owner }}/trubanb-notification-service:${{ needs.release.outputs.new_release_version }}
            --destination=ghcr.io/${{ github.repository_owner }}/trubanb-notification-service:latest
            --cache=true
            --cache-repo=ghcr.io/${{ github.repository_owner }}/trubanb-notification-service-cache
            --cache-ttl=168h
            --compressed-caching=false
            --push-retry=3
        env:
          DOCKER_CONFIG: /tmp/kaniko
